.gitmessage.txt, projects/admin/src/app/record/document/detail/detail.component.ts, projects/admin/src/app/record/institution/detail/detail.component.ts, projects/admin/src/app/record/user/detail/detail.component.ts
* Adds commit message template for consistency in commit messages between RERO projects.
=> project: add commit message template

projects/admin/src/app/deposit/editor/editor.component.html, projects/admin/src/app/deposit/editor/editor.component.ts, projects/admin/src/app/deposit/upload/upload.component.ts
* Populates deposit data by extracting metadata from main PDF.
* Closes #7.
=> deposit: populate deposit data from PDF data

projects/admin/src/app/app.module.ts, projects/admin/src/app/core/highlight-json.pipe.spec.ts, projects/admin/src/app/core/highlight-json.pipe.ts, projects/admin/src/app/deposit/editor/editor.component.html, projects/admin/src/app/deposit/editor/editor.component.spec.ts, projects/admin/src/app/deposit/editor/editor.component.ts, projects/admin/src/styles.scss
* Adds a button to preview deposit data.
* Adds a button to preview JSON data.
* Adds a pipe to highlight a JSON string.
* Moves save and publish buttons.
=> deposit: change view mode

projects/admin/src/app/deposit/confirmation/confirmation.component.html, projects/admin/src/app/deposit/deposit.service.ts, projects/admin/src/app/deposit/editor/editor.component.ts
* Fixes the user check for accessing to deposit.
* Adds a generic method to handle error in deposit service.
* Adds a confirmation message and removes summary in confirmation page.
* Refactors "publish" method in editor component.
=> deposit: publish a deposit

projects/admin/src/app/app.module.ts, projects/admin/src/app/deposit/brief-view/brief-view.component.html, projects/admin/src/app/deposit/brief-view/brief-view.component.spec.ts, projects/admin/src/app/deposit/brief-view/brief-view.component.ts, projects/admin/src/app/deposit/confirmation/confirmation.component.html, projects/admin/src/app/deposit/deposit.service.ts, projects/admin/src/app/deposit/editor/editor.component.html, projects/admin/src/app/deposit/editor/editor.component.spec.ts, projects/admin/src/app/deposit/editor/editor.component.ts, projects/admin/src/app/deposit/review/review.component.html, projects/admin/src/app/deposit/review/review.component.spec.ts, projects/admin/src/app/deposit/review/review.component.ts, projects/admin/src/app/deposit/upload/upload.component.html, projects/admin/src/app/deposit/upload/upload.component.ts, projects/admin/src/app/user.service.ts
* Creates a review component which can manage the moderator's review.
* Adds button to review the deposit in brief view.
* Adds a method in deposit service to check if logged user can access to deposit.
* Closes #12.
=> deposit: review a deposit

projects/admin/src/app/app.component.html, projects/admin/src/app/deposit/brief-view/brief-view.component.html, projects/admin/src/app/deposit/brief-view/brief-view.component.ts, projects/admin/src/app/deposit/deposit.service.ts, projects/admin/src/app/deposit/editor/editor.component.ts, projects/admin/src/app/deposit/review/review.component.ts, projects/admin/src/app/deposit/upload/upload.component.ts, projects/admin/src/app/record/user/detail/detail.component.html, projects/admin/src/app/record/user/user.component.html
* Uses user's full name instead of last name and first name.
* Fixes loading disappearing too fast when uploading a file.
* Displays number of logs after "History" title.
* Displays if deposit is new (no review had been done).
* Closes #15.
=> deposits: various changes

.github/workflows/main.yml
* Triggers a workflow when a pull request is pushed.
=> project: trigger workflow on pushing pull request

projects/sonar/src/app/_layout/admin/admin.component.html
* Decreases spinner background opacity.
=> project: Spinner background

projects/sonar/src/app/deposit/editor/editor.component.html, projects/sonar/src/app/deposit/editor/editor.component.ts
* Fixes an error during process when a deposit is done without file.
=> deposit: deposit without file

package-lock.json, package.json, projects/sonar/src/app/app.module.ts, projects/sonar/src/app/record/document/detail/detail.component.html, projects/sonar/src/app/record/document/document.component.html, projects/sonar/src/app/translations/i18n/de.json, projects/sonar/src/app/translations/i18n/en.json, projects/sonar/src/app/translations/i18n/fr.json, projects/sonar/src/app/translations/i18n/it.json, projects/sonar/src/app/translations/loader/translate-loader.spec.ts, projects/sonar/src/app/translations/loader/translate-loader.ts, projects/sonar/src/app/translations/manual_translations.ts, tsconfig.json
* Configures translations for the project.
* Add manual translations files
* Closes #34.
=> project: Configure translations

projects/sonar/src/app/deposit/deposit.service.ts, projects/sonar/src/app/deposit/editor/editor.component.ts
* Extracts metdata from PDF only when user specifically wants it.
=> deposit: PDF metadata extraction

projects/sonar/src/app/app.module.ts, projects/sonar/src/app/core/file-link.pipe.ts, projects/sonar/src/app/deposit/editor/editor.component.html, projects/sonar/src/app/deposit/editor/editor.component.spec.ts, projects/sonar/src/app/deposit/editor/editor.component.ts, projects/sonar/src/app/deposit/upload/upload.component.html, proxy.conf.json
* Adds a preview for PDF files in deposit process.
* Allows to upload not only PDF files.
* Modifies fileLink pipe to get preview URL.
=> deposit: PDF preview

projects/sonar/src/app/record/document/detail/detail.component.html, projects/sonar/src/app/record/document/detail/detail.component.ts, proxy.conf.json
* Adds a file preview in document detail view.
=> documents: File preview

projects/sonar/src/app/deposit/editor/editor.component.html
* Fixes display of file preview for main file.
* Changes link to download a file.
=> deposit: fix file preview

projects/sonar/src/app/deposit/editor/editor.component.ts, tslint.json
* Updates files in editor when a file is removed in first step of process.
=> deposit: update files in editor

projects/sonar/src/app/record/document/detail/detail.component.html, projects/sonar/src/app/record/document/document.component.html
* Display creators of the documents in brie views.
=> documents: display contributors in brief views

projects/sonar/src/app/app-routing.module.ts
* Changes organisation key from "usi" to "unisi"
=> organisation: change organisation key

projects/sonar/src/app/record/document/document.component.html, projects/sonar/src/app/record/document/document.component.ts
* Checks main file permission on brief views.
* Shows embargo date when specified.
=> documents: check file permission on brief views

projects/sonar/src/app/_layout/admin/admin.component.html, projects/sonar/src/app/translations/i18n/de.json, projects/sonar/src/app/translations/i18n/en.json, projects/sonar/src/app/translations/i18n/fr.json, projects/sonar/src/app/translations/i18n/it.json, projects/sonar/src/app/translations/i18n/messages.json
* Adds a link to public interface to user dropdown menu.
* Uses translate directive for the other links in user dropdown.
* Closes #61.
=> navigation: add link to public interface

package-lock.json, package.json
* Upgrades ng-core to version 0.2.1.
=> dependency: upgrade ng-core

projects/sonar/src/app/record/user/detail/detail.component.html
* Improves the display of users in detail view.
=> users: improve the display of users.

projects/sonar/src/app/record/organisation/detail/detail.component.html
* Improves the display of organisations in detail view.
=> organisations: improve the display of organisations.

projects/sonar/src/app/record/document/aggregation-filter.ts
* Translates document types bucket in the aggregation.
* Closes #67.
=> search: translate document types

projects/sonar/src/app/translations/i18n/de.json, projects/sonar/src/app/translations/i18n/en.json, projects/sonar/src/app/translations/i18n/fr.json, projects/sonar/src/app/translations/i18n/it.json, projects/sonar/src/app/translations/i18n/messages.json, projects/sonar/src/app/translations/manual_translations.ts
* Adds translation for role publisher.
=> user: add role publisher

projects/sonar/src/app/deposit/editor/editor.component.ts
* Takes into account of form options passed by JSON schema.
* Takes into account of hideExpression passed by JSON schema.
=> deposit: editor form options

projects/sonar/src/app/deposit/upload/upload.component.ts
* Fixes the error occuring when a deposit is done without file.
* Fixes #90.
=> deposit: error in deposit without file

.prettierrc.json, projects/sonar/src/app/app.module.ts, projects/sonar/src/app/interceptor/http.interceptor.ts
* Adds a HTTP interceptor to disable cache and correctly encode HTTP params.
* Adds prettier config file.
* Closes #89.
=> api: HTTP interceptor

projects/sonar/src/index.html, projects/sonar/src/styles.scss
* Changes font family from `Roboto Condensed` to `Roboto`.
=> design: change font family.

projects/sonar/src/app/_layout/admin/admin.component.html, projects/sonar/src/app/app-routing.module.ts
* Adds a route to edit user logged profile.
see https://github.com/rero/sonar/pull/235
=> account: profile edition

projects/sonar/src/app/deposit/editor/editor.component.html, projects/sonar/src/app/deposit/editor/editor.component.ts, projects/sonar/src/app/record/document/detail/detail.component.html
* Displays role and ORCID number in preview.
* Fixes the display of date in preview.
* Fixes the display of classification in preview.
* Fixes the display of other title in preview.
* Displays role and ORCID number in document detail view.
=> deposits: improve preview display

projects/sonar/src/app/record/user/detail/detail.component.html, projects/sonar/src/app/record/user/user.component.html, projects/sonar/src/app/user.service.ts, projects/sonar/src/assets/i18n/de.json, projects/sonar/src/assets/i18n/en.json, projects/sonar/src/assets/i18n/fr.json, projects/sonar/src/assets/i18n/it.json, projects/sonar/src/assets/i18n/messages.json
* Changes checks of the user role as user has now only one role.
* Changes the display of role in users brief views.
* Removes useless detail views for users and organisations.
=> users: limit user to one role

projects/sonar/src/app/deposit/editor/editor.component.ts
* Fixes a compilation error by forcing fieldSchema to `any` type.
=> project: compilation error

README.md
* Updates README file by adding badges and removing auto-generated text from angular.
=> document: update README file

projects/sonar/src/assets/i18n/de.json, projects/sonar/src/assets/i18n/en.json, projects/sonar/src/assets/i18n/fr.json, projects/sonar/src/assets/i18n/it.json, projects/sonar/src/assets/i18n/messages.json
* Updates translations catalogs for all languages.
=> translations: update catalogs

projects/sonar/src/app/app-routing.module.ts
* Adds a configuration to enable search in full-text field.
* Closes #126.
=> documents: enable search in full-text

projects/sonar/src/app/record/user/user.component.html
* Displays an information if the user does not belong to an organisation.
=> users: display organisation information

package-lock.json, package.json
* Upgrades `ng-core` to version 0.10.0.
=> dependencies: upgrade ng-core library

projects/sonar/src/app/app-routing.module.ts, projects/sonar/src/manual_translations.ts
* Configures facet to filter users not attached to any organisation.
=> users: facet for users without organisation

projects/sonar/src/manual_translations.ts
* Updates `unisi` key to `usi`, to use the right acronym.
=> translations: update `unisi` key

projects/sonar/src/app/record/document/detail/detail.component.html, projects/sonar/src/app/record/document/document.component.html
* Displays the meeting formatted text in the documents brief and detailed views.
=> documents: display meeting text

package.json
=> compiler: remove ngcc in post install

projects/sonar/src/app/deposit/brief-view/brief-view.component.html, projects/sonar/src/app/deposit/editor/editor.component.html, projects/sonar/src/app/deposit/editor/editor.component.ts, projects/sonar/src/app/record/document/detail/detail.component.html, projects/sonar/src/app/record/document/document.component.html
* Displays title with carriage returns in deposit preview.
* Displays title with carriage returns in documents and deposits brief views, and in document detail views.
* Displays abstract with carriage returns in documents detail views.
* Handles validation messages coming from JSON schema in deposit editor.
=> deposit: improve editor

package-lock.json, package.json
Upgrades ng-core library to version 1.1.2.
=> dependencies: upgrade ng-core

projects/sonar/src/app/_layout/admin/admin.component.html, projects/sonar/src/app/deposit/brief-view/brief-view.component.html, projects/sonar/src/app/record/user/detail/detail.component.html, projects/sonar/src/app/record/user/user.component.html
* Changes all occurrences of `full_name` in templates.
* Closes rero/sonar#222.
=> users: separate first name and last name.

projects/sonar/src/assets/i18n/de.json, projects/sonar/src/assets/i18n/en.json, projects/sonar/src/assets/i18n/fr.json, projects/sonar/src/assets/i18n/it.json
Italian translated at 100.0% (327 of 327 strings)
French translated at 100.0% (327 of 327 strings)
English translated at 100.0% (327 of 327 strings)
German translated at 100.0% (327 of 327 strings)
Co-authored-by: Sébastien Délèze <sebastien.deleze@rero.ch>
Translate-URL: https://hosted.weblate.org/projects/rero_plus/sonar-ui/
Translation: RERO+/sonar-ui
=> translations: update catalog

projects/sonar/src/styles.scss
Adds styles for bootstrap datepicker.
=> styles: add styles for datepicker

projects/sonar/src/app/deposit/editor/editor.component.ts
* Handles custom form types from JSON schema and not only the textarea type.
* Contributes to make rero/sonar#530 work.
=> editor: handle custom form type

projects/sonar/src/app/app-routing.module.ts, projects/sonar/src/app/app.module.ts, projects/sonar/src/app/record/hepvs/project/detail/detail.component.html, projects/sonar/src/app/record/hepvs/project/detail/detail.component.ts
* Adds a custom detail view for HEP Valais projects.
* Closes rero/sonar#455.
=> projects: detail view for HEP Valais

package-lock.json, package.json
=> dependencies: fix security issues

projects/sonar/src/app/app-routing.module.ts
=> projects: enable CSV export

projects/sonar/src/app/app-routing.module.ts, projects/sonar/src/app/app.module.ts, projects/sonar/src/app/record/hepvs/project/detail/detail.component.html, projects/sonar/src/app/record/project/brief-view/brief-view.component.html, projects/sonar/src/app/record/project/detail/detail.component.ts, projects/sonar/src/app/record/validation/constants.ts, projects/sonar/src/app/record/validation/validation.component.html, projects/sonar/src/app/record/validation/validation.component.ts
* Creates a component for managing validation.
* Adds the validation component to projet detail view.
* Displays if project is published in projet brief view.
* Enables facet for projects status.
=> projects: validation workflow

projects/sonar/src/app/_layout/admin/admin.component.html, projects/sonar/src/app/app-routing.module.ts, projects/sonar/src/app/app.module.ts, projects/sonar/src/app/deposit/editor/editor.component.html, projects/sonar/src/app/record/collection/brief-view/brief-view.component.html, projects/sonar/src/app/record/collection/brief-view/brief-view.component.ts, projects/sonar/src/app/record/collection/detail/detail.component.html, projects/sonar/src/app/record/collection/detail/detail.component.ts, projects/sonar/src/app/record/document/detail/detail.component.html
* Adds configuration to manage collections in administration.
* Creates a brief view to display collections items.
* Creates a detail view to display a collection.
* Renames aggregation `specific_collection` to `collection`.
* Adds a link to collections in admin menu.
* Displays collections information in deposit preview.
* Displays collections information in document detail view.
* Enables editor long mode for collections.
=> projects: add resource for collections

projects/sonar/src/app/deposit/editor/editor.component.html, projects/sonar/src/styles.scss
* Updates the styles to delimitate objects.
* Adds a separation between form and deposit summary in the last step.
=> deposits: improve process

projects/sonar/src/app/record/document/detail/detail.component.html, projects/sonar/src/app/record/document/detail/detail.component.ts
* Hides Dewey classification in documents detail views.
=> documents: hide Dewey classification

projects/sonar/src/app/record/document/detail/detail.component.html
* Makes classification and subjects clickable in documents detail views.
=> documents: classification and subjects clickable

projects/sonar/src/app/_layout/admin/admin.component.ts, projects/sonar/src/app/deposit/confirmation/confirmation.component.html, projects/sonar/src/app/deposit/confirmation/confirmation.component.ts, projects/sonar/src/app/user.service.ts
* Adds a link to the public interface in the confirmation page.
* Adds a link to deposit another publication in the confirmation page.
* Moves the function for getting the public interface URL in the user
service.
=> deposits: add links in confirmation page

projects/sonar/src/app/app-routing.module.ts, projects/sonar/src/app/record/document/detail/detail.component.html, projects/sonar/src/manual_translations.ts
* Displays more info for masked property.
* Displays `masked` facet.
=> documents: display more info for masked property

projects/sonar/src/app/app-routing.module.ts, projects/sonar/src/app/record/project/brief-view/brief-view.component.html
=> records: add configuration for sorting records

projects/sonar/src/app/deposit/editor/editor.component.html, projects/sonar/src/app/deposit/editor/editor.component.ts
* Allows to import record data from swisscovery.
=> deposits: import record from swisscovery

package-lock.json, package.json, projects/sonar/src/app/record/organisation/detail/detail.component.html, projects/sonar/src/app/record/organisation/organisation.component.html
* Updates detail view to show multilingual footer field.
=> organisations: multilingual footer field

projects/sonar/src/app/deposit/editor/editor.component.ts
* Forces to save a new deposit before validate or submit a new deposit.
Co-Authored-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>
=> deposit: fix allow submit and validation with save

CHANGELOG.md, package-lock.json, package.json
Co-Authored-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>
=> release: version 1.4.1

projects/sonar/src/app/app-translate-loader.spec.ts, projects/sonar/src/app/app-translate-loader.ts, projects/sonar/src/app/app.module.ts, projects/sonar/src/app/deposit/editor/editor.component.html, projects/sonar/src/app/deposit/editor/editor.component.ts, projects/sonar/src/app/record/document/detail/detail.component.html, projects/sonar/tests/utils.ts
* Adds a class to override translations for custom fields.
* Closes rero/sonar#706.
=> deposit: allow custom fields to be entered on submission

projects/sonar/src/app/_layout/admin/admin.component.ts, projects/sonar/src/app/app-translate-loader.spec.ts, projects/sonar/src/app/app-translate-loader.ts, projects/sonar/src/app/app.component.ts, projects/sonar/src/app/app.module.ts, projects/sonar/tests/utils.ts
* Closes rero/sonar#741.
- stabilizing the interface language
- Change the language on different pages of the site and then navigate.
=> interface: instability of the interface language

CHANGELOG.md, package-lock.json, package.json
Co-Authored-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>
=> release: version 1.4.2

projects/sonar/src/app/app-config.service.ts, projects/sonar/src/app/app.component.ts, projects/sonar/src/app/record/document/detail/detail.component.ts, projects/sonar/src/app/record/document/document.component.html, projects/sonar/src/app/record/document/document.component.ts, projects/sonar/src/environments/environment.prod.ts, projects/sonar/src/environments/environment.ts, projects/sonar/src/index.html
* Adds new configuration to store view param.
* Adds a control for the organisation tag on the brief view of the document.
=> documents: remove organisation tag

projects/sonar/src/app/record/document/file/file.component.html
=> documents: hide label file in the detailed view

projects/sonar/src/app/deposit/editor/editor.component.html, projects/sonar/src/app/record/document/detail/detail.component.html, projects/sonar/src/manual_translations.ts
* Changes the title field on detailed view with "Submitted to" for preprint.
=> document and preprint: label change for preprint

.github_changelog_generator
- Add default parameters file for github_changelog_generator
=> documentation: improve changelog generation

CHANGELOG.md, package-lock.json, package.json
Co-Authored-by: Pascal Repond <pascal.repond@rero.ch>
=> release: v1.4.3

projects/sonar/src/app/app.module.ts, projects/sonar/src/app/pipe/contributors.pipe.spec.ts, projects/sonar/src/app/pipe/contributors.pipe.ts, projects/sonar/src/app/record/document/contribution.interface.ts, projects/sonar/src/app/record/document/detail/contribution/contribution.component.html, projects/sonar/src/app/record/document/detail/contribution/contribution.component.ts, projects/sonar/src/app/record/document/detail/contributions/contributions.component.html, projects/sonar/src/app/record/document/detail/contributions/contributions.component.ts, projects/sonar/src/app/record/document/detail/detail.component.html, projects/sonar/src/app/record/document/detail/detail.component.ts
* Addsfields: notes, contentNote, editionStatement, series,
additionalMaterials, otherMaterialCharacteristics, oa_status.
* Splits the data in the contributions field (meeting and other).
* Closes rero/sonar#723.
=> documents: add and improve fields on detailed view

projects/sonar/src/app/record/document/detail/contributions/contributions.component.html, projects/sonar/src/app/record/document/detail/contributions/contributions.component.ts, projects/sonar/src/app/record/document/detail/detail.component.html, projects/sonar/src/app/record/document/detail/detail.component.ts
* Closes https://github.com/rero/sonar/issues/841.
Co-Authored-by: Johnny Mariéthoz <johnny.mariethoz@rero.ch>
=> documents: fix tooltip on contributions

projects/sonar/src/app/record/document/detail/detail.component.html, projects/sonar/src/app/record/document/detail/detail.component.ts, projects/sonar/src/app/record/document/document.component.html, projects/sonar/src/app/record/document/file/file.component.html, projects/sonar/src/app/record/document/file/file.component.ts
Add record statistics section in admin view.
Co-Authored-by: Valeria Granata <valeria@chaw.com>
Issue: https://github.com/rero/sonar/issues/400
This PR depends on:
https://github.com/rero/sonar/pull/857
=> record: add record statistics section in admin view

projects/sonar/src/app/app.module.ts, projects/sonar/src/app/record/document/contribution/contribution.component.html, projects/sonar/src/app/record/document/contribution/contribution.component.ts, projects/sonar/src/app/record/document/detail/contributions/contributions.component.html, projects/sonar/src/app/record/document/document.component.html, projects/sonar/src/app/record/document/document.component.ts, projects/sonar/src/index.html
=> documents: add search link on the author's name

CHANGELOG.md, package-lock.json, package.json
* Uses ng-core `v^1.16.0`.
Co-Authored-by: Pascal Repond <pascal.repond@rero.ch>
=> release: v1.6.0

projects/sonar/src/app/app-routing.module.ts, projects/sonar/src/app/record/document/detail/contributions/contributions.component.ts, projects/sonar/src/app/record/document/detail/detail.component.ts
- dependencies: move to angular 14
- documents: add files permissions
=> documents: add files permissions

CHANGELOG.md, package-lock.json, package.json
=> release: v14.0.0

projects/sonar/src/app/app-routing.module.ts, projects/sonar/src/manual_translations.ts
- Closes https://github.com/rero/sonar/issues/957.
=>  translations: translate search field label 
