package-lock.json, package.json, projects/sonar/src/app/record/document/detail/detail.component.html, projects/sonar/src/app/record/document/document.component.html
* Adapts brief and detail views for documents after import of RERODOC data.
* Updates ng-core library.
* Closes #36.
=> documents: Adapt brief and detail views

projects/sonar/src/app/record/document/detail/detail.component.html, projects/sonar/src/app/record/document/document.component.html, projects/sonar/src/app/record/document/document.component.ts
* Adds thumbnails for documents in brief view.
* Changes link to detail in brief view.
* Adds label info of file in detail view.
=> documents: add thumbnails in brief view

projects/sonar/src/app/deposit/editor/editor.component.ts
* Shows a spinner when a deposit is validated, before redirecting to confirmation page.
=> deposit: show spinner during validation

package-lock.json, package.json
* Upgrades "acorn" dependency to version 6.4.1 or later.
* Upgrades "minimist" dependency to version 0.2.1 or later.
* Upgrades "kind-of" dependency to version 6.0.3 or later.
* Reorders entries and dependencies in package.json file using command "npx sort-package-json".
* Moves translations extraction tools to the dev dependencies section.
=> security: update dependencies

projects/sonar/src/app/app-routing.module.ts, projects/sonar/src/app/record/document/document.component.ts
* Enables long mode for documents editor.
* Renames property for checking file restriction from "restricted" to "restriction".
=> documents: improve editor

projects/sonar/src/app/deposit/brief-view/brief-view.component.html
* Shows the deposits for the publishers (This has been done in the check permissions PR).
* Uses `translate` directives instead pipe.
* Displays history for all users not only moderators.
1. Login as publisher
2. Create one or several deposits.
3. Check the logged user has access to his deposits.
4. Check the logged user can see the history of his deposits.
=> deposits: show deposits for publishers

projects/sonar/src/app/app-config.service.ts, projects/sonar/src/app/app-routing.module.ts, projects/sonar/src/app/record/document/aggregation-filter.ts, projects/sonar/src/app/record/organisation/detail/detail.component.html, projects/sonar/src/assets/i18n/de.json, projects/sonar/src/assets/i18n/en.json, projects/sonar/src/assets/i18n/fr.json, projects/sonar/src/assets/i18n/it.json, projects/sonar/src/assets/i18n/messages.json
* Uses one route for all organisations search page.
* Updates route data according to the `view` parameter.
* Adds the values for `isShared` and `isDedicated` properties in organisation's detail view.
* Hides aggregation for organisation if the view code is not global.
See https://github.com/rero/sonar/pull/234
=> organisations: search route

projects/sonar/src/app/_layout/admin/admin.component.html, projects/sonar/src/app/app-routing.module.ts, projects/sonar/src/assets/i18n/de.json, projects/sonar/src/assets/i18n/en.json, projects/sonar/src/assets/i18n/fr.json, projects/sonar/src/assets/i18n/it.json, projects/sonar/src/assets/i18n/messages.json, projects/sonar/src/manual_translations.ts
* Renames role `publisher` to `submitter`.
* Closes #250.
=> users: rename role publisher

projects/sonar/src/app/app-config.service.ts, projects/sonar/src/app/app-routing.module.ts, projects/sonar/src/app/app.module.ts, projects/sonar/src/app/record/document/document.component.html, projects/sonar/src/app/record/document/document.component.ts, projects/sonar/src/app/record/document/publication.pipe.spec.ts, projects/sonar/src/app/record/document/publication.pipe.ts, projects/sonar/src/index.html, projects/sonar/src/styles.scss, projects/sonar/tests/utils.ts
* Improves the display of brief views for documents.
* Adds a `publicationPipe` for displaying text for document's publications.
* Adds a configuration object to facilitate testing.
* Closes rero/sonar#253.
=> documents: improve brief views

projects/sonar/src/app/_layout/admin/admin.component.html, projects/sonar/src/app/_layout/admin/admin.component.spec.ts, projects/sonar/src/app/app.component.html, projects/sonar/src/app/app.component.spec.ts, projects/sonar/src/app/app.module.ts
* Removes declaration of `ngx-spinner` module as it is exported from ng-core.
* Changes spinner type and size.
=> project: use ngx-spinner from ng-core.

projects/sonar/src/app/record/document/detail/detail.component.html
* Displays correctly the date for provision activities field.
=> document: display date for provision activities

projects/sonar/src/app/app.module.ts, projects/sonar/src/app/deposit/editor/editor.component.html, projects/sonar/src/app/deposit/editor/editor.component.spec.ts, projects/sonar/src/app/deposit/editor/editor.component.ts, projects/sonar/src/app/record/document/detail/detail.component.html, projects/sonar/src/app/record/document/document.component.html
* Adds the dissertation field to the submission form.
* Displays dissertation text in documents brief views.
* Displays dissertation text in documents detail views.
* Displays dissertation text in deposit summary view.
* Adds `DatePipe` to providers for using it in components.
=> documents: add dissertation property

projects/sonar/src/app/deposit/brief-view/brief-view.component.html, projects/sonar/src/app/deposit/editor/editor.component.html, projects/sonar/src/app/deposit/upload/upload.component.html
* Changes the target of the review button to point to the first step of the deposit process (file upload).
* Shows the review panel only in the last step of deposit process.
* Closes #123.
=> deposit: improve review

projects/sonar/src/app/app-routing.module.ts, projects/sonar/src/app/record/organisation/detail/detail.component.html, projects/sonar/src/app/record/organisation/organisation.component.html
Files management is enabled for organisations for adding a logo to the organisation.
* Enables files handling for organisations.
* Displays description in the brief and detail views.
* Add a link to organisation's detail in brief views.
=> organisations: enable files management

projects/sonar/src/app/app-routing.module.ts
* Set the maxium size for aggregations, before showing the `show more` link.
* Closes #131.
=> records: set maximum size for aggregations

projects/sonar/src/app/record/document/document.component.ts
This commit ensures that's the right thumbnail (corresponding to the main file) which is displayed in the brief views.
* Changes thumbnail loading method to take the thumbnail corresponding to the main file.
=> documents: display thumbnails in brief views.

projects/sonar/src/app/app-routing.module.ts
* Sorts files by `order` property.
* Filter files to display only files of type `file`.
* Changes the way to enable files management, uses `files.enabled` instead of `filesEnabled`.
=> documents: add configurations for handling files

projects/sonar/src/manual_translations.ts
Remove manual translations for organisations as the values in the facet are translated in backend
* Removes manual translations for organisations.
=> organisations: remove manual translations

projects/sonar/src/app/core/step/step.component.html, projects/sonar/src/app/core/step/step.component.ts, projects/sonar/src/app/deposit/editor/editor.component.html, projects/sonar/src/app/deposit/editor/editor.component.ts, projects/sonar/src/app/record/document/detail/detail.component.html, projects/sonar/src/manual_translations.ts
This commit adds a license field in the last step of deposit process. The license is displayed in the document's detail view.
* Displays the license field in the `diffusion` step of deposit process.
* Emits an event when a step is clicked, for resetting the current view to `form` when the user changes the step.
* Displays the submit button only if the license has been saved.
* Fixes the display of `identifiedBy` and `dissertation` fields in preview.
* Displays the license in document's detail view.
=> deposit: add license

projects/sonar/src/app/app-routing.module.ts
* Enables long mode fore documents editor as it's no more enabled by default.
=> documents: enable editor long mode

projects/sonar/src/app/app-routing.module.ts, projects/sonar/src/app/app.module.ts, projects/sonar/src/app/record/document/detail/detail.component.html, projects/sonar/src/app/record/document/detail/detail.component.ts, projects/sonar/src/app/record/document/document.component.html, projects/sonar/src/app/record/document/document.component.ts, projects/sonar/src/app/record/document/document.interface.ts, projects/sonar/src/app/record/document/file/file.component.html, projects/sonar/src/app/record/document/file/file.component.spec.ts, projects/sonar/src/app/record/document/file/file.component.ts
This PR aims to display files of several types. It refactors the way to display files as with the old manner, only PDF files were well displayed.
* Hides `links` and `thumbnail` data in the file information.
* Adds a document file component to display files.
* Uses the new component to display files in brief and detail views.
* Removes useless code for files in brief and detail components.
* Adds an interface to represent a document file.
* Displays modal preview programmitically, as the action is sent by an output emitter.
=> documents: display files

projects/sonar/src/app/_layout/admin/admin.component.html, projects/sonar/src/app/app-routing.module.ts, projects/sonar/src/app/app.module.ts, projects/sonar/src/app/core/step/step.component.html, projects/sonar/src/app/deposit/editor/editor.component.html, projects/sonar/src/app/deposit/editor/editor.component.ts, projects/sonar/src/app/deposit/upload/upload.component.html, projects/sonar/src/app/record/document/detail/detail.component.html, projects/sonar/src/app/record/document/detail/detail.component.ts, projects/sonar/src/app/record/identifier/identifier.component.html, projects/sonar/src/app/record/identifier/identifier.component.spec.ts, projects/sonar/src/app/record/identifier/identifier.component.ts, projects/sonar/src/app/record/project/brief-view/brief-view.component.html, projects/sonar/src/app/record/project/brief-view/brief-view.component.ts, projects/sonar/src/app/record/project/detail/detail.component.html, projects/sonar/src/app/record/project/detail/detail.component.ts, projects/sonar/src/manual_translations.ts, projects/sonar/src/styles.scss
* Activates `project` resource in route configuration.
* Creates brief view for `project` resource.
* Creates detail view for `project` resource.
* Adds an entry for the projects in documents menu.
* Creates a component for displaying `identifiedBy` field.
=> projects: activate resource

projects/sonar/src/app/record/identifier/identifier.component.html
* Adds a link for identifiers of type `DOI`.
=> documents: set DOI clickable

projects/sonar/src/app/deposit/upload/upload.component.ts
* Limits uploaded files to 500Mb.
* Closes rero/sonar#412.
=> deposits: limit uploads to 500Mb

projects/sonar/src/app/_layout/admin/admin.component.html, projects/sonar/src/app/_layout/admin/admin.component.ts
* Adds the dedicated context to the link for the public interface, if user's organisation is flagged as dedicated.
* Closes rero/sonar#499.
=> project: update link to public interface

projects/sonar/src/app/app-routing.module.ts, projects/sonar/src/app/deposit/brief-view/brief-view.component.html, projects/sonar/src/app/deposit/upload/upload.component.ts
* Uses `id` property instead of `metadata.pid` as this property not exists anymore with resource management with `invenio-records-resources.` module.
* Flags `projects` resource a managed by `invenio-records-resources`.
=> resources: use `id` property for records

projects/sonar/src/app/app-routing.module.ts
Configures a filter to search only for open access documents.
=> documents: configure open access filter

projects/sonar/src/app/app-routing.module.ts
* Changes `open_access` filter value to be able to use it with terms filters in backend.
=> documents: change `open_access` filter value

projects/sonar/src/app/app-routing.module.ts, projects/sonar/src/app/app.component.ts, projects/sonar/src/app/pipe/language-value.pipe.ts, projects/sonar/src/app/record/document/detail/detail.component.html, projects/sonar/src/app/record/document/detail/detail.component.ts, projects/sonar/src/app/record/document/document.component.html, projects/sonar/src/app/record/hepvs/project/detail/detail.component.html, projects/sonar/src/app/record/organisation/detail/detail.component.html, projects/sonar/src/app/record/project/detail/detail.component.html, proxy.conf.json
* Enables long mode for organisations editor.
* Adds custom fields in aggregations order.
* Displays the custom fields in documents detail view.
* Fixes an issue if document's abstract does not exist.
* Displays configuration for custom fields in organisations detail view.
=> documents: handle custom fields for organisations

projects/sonar/src/app/app.component.ts
* Sets the language from the html tag and not from cookie, as the backend has the right language value.
* Does not set the cookie anymore when the language is changed.
* Fixes rero/sonar#598.
=> lang: fix language setting

projects/sonar/src/app/deposit/editor/editor.component.ts
Stores the document date when metadata an extracted from PDF.
=> deposits: store document date extracted from PDF

projects/sonar/src/app/record/document/detail/detail.component.html
* Displays an icon to inform user that a document is masked in the professional detail view.
=> documents: display `masked` property info

projects/sonar/src/app/app-routing.module.ts
* Removes `missing_organisation` user as it is no more possible to
create a user without an associated organisation.
=> users: remove `missing_organisations` aggregation

projects/sonar/src/app/_layout/admin/admin.component.html, projects/sonar/src/app/app-routing.module.ts, projects/sonar/src/app/app.module.ts, projects/sonar/src/app/record/document/detail/detail.component.html, projects/sonar/src/app/record/document/document.component.html, projects/sonar/src/app/record/organisation/detail/detail.component.html, projects/sonar/src/app/record/organisation/detail/detail.component.ts, projects/sonar/src/app/record/subdivision/brief-view/brief-view.component.html, projects/sonar/src/app/record/subdivision/brief-view/brief-view.component.ts, projects/sonar/src/app/record/subdivision/detail/detail.component.html, projects/sonar/src/app/record/subdivision/detail/detail.component.ts, projects/sonar/src/app/record/user/detail/detail.component.html, projects/sonar/src/app/record/user/user.component.html
* Adds configuration to manage subdivisions in administration.
* Creates a brief view to display subdivisions items.
* Creates a detail view to display a subdivision.
* Adds a link to subdivisions in admin menu.
* Reorganizes the admin navigation.
* Adds facet for `subdivisions` in documents.
* Adds facet for `subdivisions` in deposits.
* Adds facet for `subdivisions` in users.
* Displays subdivisions info in document detail view in admin.
* Displays subdivisions info in the user detail view.
* Displays organisations and subdivisions in document brief view.
* Displays organisations and subdivisions in document detail view below the title.
* Displays subdivisions and collections in organisation detail view.
* Displays subdivisions in user brief view.
* Enables editor long mode for users.
* …
=> project: add resource for subdivisions

projects/sonar/src/app/app-config.service.ts, projects/sonar/src/app/app-routing.module.ts, projects/sonar/src/app/record/document/aggregation-filter.ts
* Retrieves the aggregations order from backend.
* Removes unused property `globalSearchViewCode`.
=> documents: aggregations order from backend

projects/sonar/src/app/_layout/admin/admin.component.html, projects/sonar/src/app/_layout/admin/admin.component.ts, projects/sonar/src/app/app-initializer.service.spec.ts, projects/sonar/src/app/app-initializer.service.ts, projects/sonar/src/app/app-routing.module.ts, projects/sonar/src/app/app.module.ts, projects/sonar/src/app/user.service.ts
Remove the "Collections" and "Subdivisions" entries
in the administration menu for shared organizations.
* Closes rero/sonar#751.
- Check administration menu with user connected with shared organisation.
=> menu: remove entries on administration menu

projects/sonar/src/app/record/document/detail/detail.component.ts
The languages of the abstracts that are not in the preferred
sorting languages are added at the end of the list and sorted
alphabetically by language code.
* Fixes Sentry SONAR-EA.
=> documents: fix abstracts sort

projects/sonar/src/app/app-routing.module.ts
* Use only extractor instead of instant translate for labels in the route. As they have no knowledge of langugage, they are translated by ng-core.
=> fix: search components translations
